import React, { useCallback, useEffect, useRef, useState } from 'react';
import { ActivityIndicator, Alert, AppState, BackHandler, Image, KeyboardAvoidingView, Linking, Platform, Pressable, RefreshControl, ScrollView, StyleSheet, Text, TextInput, useWindowDimensions, View } from 'react-native';
import { SafeAreaProvider, SafeAreaView } from 'react-native-safe-area-context';
import { StatusBar } from 'expo-status-bar';
import { acceptLogin, API_URL, forgetSession, logout, refreshSession, request, setExpiryHandler, SITE_URL } from './src/api';
import { ContactRequests } from './src/ContactRequests';
import { ContactDoctor } from './src/ContactDoctor';
import { SecuritySettings } from './src/SecuritySettings';
import { DoctorAppointmentActions } from './src/DoctorAppointmentActions';
import { PatientAccount } from './src/PatientAccount';
import { AccountForms } from './src/AccountForms';
import { Appointment, dateLabel, dayKey, Doctor, labels, Notice, User } from './src/contracts';

type Tab = 'directorio' | 'citas' | 'avisos' | 'cuenta';
function Action({ title, onPress, secondary = false, disabled = false }: { title: string; onPress: () => void; secondary?: boolean; disabled?: boolean }) {
  return <Pressable accessibilityRole="button" disabled={disabled} onPress={onPress} style={[s.button, secondary && s.secondary, disabled && { opacity: .5 }]}><Text style={[s.buttonText, secondary && { color: '#125545' }]}>{title}</Text></Pressable>;
}
function Field({ placeholder, value, onChangeText, secret = false }: { placeholder: string; value: string; onChangeText: (v: string) => void; secret?: boolean }) {
  return <TextInput accessibilityLabel={placeholder} placeholder={placeholder} placeholderTextColor="#697a78" value={value} onChangeText={onChangeText} secureTextEntry={secret} autoCapitalize="none" style={s.input} />;
}
export default function App() {
  return <SafeAreaProvider><AppContent /></SafeAreaProvider>;
}
function AppContent() {
  const { width } = useWindowDimensions();
  const horizontalPadding = width < 360 ? 12 : width >= 768 ? 32 : 20;
  const [accountFormOpen, setAccountFormOpen] = useState(false);
  const [tab, setTab] = useState<Tab>('directorio'); const [user, setUser] = useState<User | null>(null);
  const [doctors, setDoctors] = useState<Doctor[]>([]); const [doctor, setDoctor] = useState<Doctor | null>(null);
  const [page, setPage] = useState(1); const [pages, setPages] = useState(1); const [search, setSearch] = useState(''); const [query, setQuery] = useState('');
  const [appointments, setAppointments] = useState<Appointment[]>([]); const [notices, setNotices] = useState<Notice[]>([]);
  const [slots, setSlots] = useState<string[]>([]); const [date, setDate] = useState(dayKey(new Date()));
  const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [code, setCode] = useState(''); const [challenge, setChallenge] = useState<string | null>(null);
  const [error, setError] = useState(''); const [busy, setBusy] = useState(false); const [loading, setLoading] = useState(false); const [updated, setUpdated] = useState<Date | null>(null);
  const generation = useRef(0); const mounted = useRef(true);
  const session = useCallback(async () => { const id = generation.current; const me = await request<User>('/auth/me'); if (mounted.current && id === generation.current) setUser(me); }, []);
  useEffect(() => { mounted.current = true; setExpiryHandler(() => { generation.current++; setUser(null); setAppointments([]); setNotices([]); setError('Tu sesión venció. Inicia sesión de nuevo.'); }); void refreshSession().then(ok => { if (ok && mounted.current) void session().catch(() => {}); }); return () => { mounted.current = false; setExpiryHandler(() => {}); }; }, [session]);
  const load = useCallback(async () => {
    const id = ++generation.current;
    setLoading(true);
    try {
      if (tab === 'directorio') {
        if (doctor) { if (doctor.bookingEnabled && /^\d{4}-\d{2}-\d{2}$/.test(date)) { const data = await request<string[]>(`/appointments/availability?professionalId=${doctor.id}&from=${date}&to=${date}`); if (id === generation.current) setSlots(data); } }
        else { const data = await request<{ items: Doctor[]; totalPages: number }>(`/professionals?limit=12&page=${page}&search=${encodeURIComponent(query)}`); if (id === generation.current) { setDoctors(data.items); setPages(data.totalPages); } }
      } else if (user && tab === 'citas') {
        const from = dayKey(new Date()); const to = dayKey(new Date(Date.now() + 30 * 86400000));
        const data = await request<Appointment[]>(user.role === 'PROFESSIONAL' ? `/appointments/me/agenda?from=${from}&to=${to}` : '/appointments/me');
        if (id === generation.current) setAppointments(data);
      } else if (user && tab === 'avisos') { const data = await request<{ items: Notice[] }>('/notifications?limit=30'); if (id === generation.current) setNotices(data.items); }
      else if (user && tab === 'cuenta') await session();
      if (id === generation.current) { setError(''); setUpdated(new Date()); }
    } catch (e) { if (id === generation.current) { setError(e instanceof Error ? e.message : 'No hay conexión.'); if (tab === 'directorio') setSlots([]); } }
    finally { if (mounted.current && id === generation.current) setLoading(false); }
  }, [tab, user?.id, user?.role, doctor, date, page, query, session]);
  useEffect(() => { void load(); const timer = setInterval(() => { if (AppState.currentState === 'active') void load(); }, 15000); const subscription = AppState.addEventListener('change', state => { if (state === 'active') void load(); }); return () => { clearInterval(timer); subscription.remove(); }; }, [load]);
  useEffect(() => { const listener = BackHandler.addEventListener('hardwareBackPress', () => { if (doctor) { setDoctor(null); setSlots([]); return true; } if (challenge) { setChallenge(null); return true; } if (tab !== 'directorio') { setAccountFormOpen(false); setTab('directorio'); return true; } return false; }); return () => listener.remove(); }, [doctor, challenge, tab]);
  async function run(action: () => Promise<void>) { if (busy) return; setBusy(true); setError(''); try { await action(); } catch(e) { setError(e instanceof Error ? e.message : 'No se pudo guardar.'); } finally { setBusy(false); } }
  async function login() { await run(async () => { const result = await request<{ accessToken?: string; mfaRequired?: boolean; challengeToken?: string }>('/auth/login','POST',{email:email.trim(), password}); if(result.mfaRequired) { setChallenge(result.challengeToken!); setPassword(''); return; } await acceptLogin(result); await session(); setPassword(''); setTab('citas'); }); }
  async function mfa() { await run(async () => { await acceptLogin(await request('/auth/mfa/verify','POST',{challengeToken:challenge,code})); await session(); setChallenge(null); setCode(''); setTab('citas'); }); }
  async function openDoctor(d: Doctor) { await run(async () => { setDoctor(await request<Doctor>(`/professionals/${encodeURIComponent(d.slug)}`)); setSlots([]); }); }
  const changeTab = (next: Tab) => { generation.current++; setTab(next); setAccountFormOpen(false); setError(''); setDoctor(null); setSlots([]); };
  function book(startsAt: string) { if (!user) { changeTab('cuenta'); return; } Alert.alert('Confirmar cita', `¿Solicitar cita el ${dateLabel(startsAt)}? No se otorgan permisos de datos de salud con esta reserva.`, [{text:'Volver',style:'cancel'},{text:'Solicitar',onPress:() => void run(async () => { await request('/appointments','POST',{professionalId:doctor!.id,startsAt}); setSlots([]); await load(); Alert.alert('Cita solicitada','Puedes consultar el estado en Citas.'); })}]); }
  return <SafeAreaView style={s.root} edges={['left', 'right', 'bottom']}><StatusBar style="light"/><SafeAreaView edges={['top']} style={s.header}><View style={s.headerContent}><Text style={s.brand}>GUÍA MÉDICA</Text><Text style={s.title}>Monagas</Text><Text style={s.subtitle}>Tu salud, más cerca.</Text></View></SafeAreaView>
    <KeyboardAvoidingView style={s.body} behavior={Platform.OS === 'ios' ? 'padding' : 'height'}><ScrollView style={s.body} contentContainerStyle={[s.content, { paddingHorizontal: horizontalPadding }]} keyboardShouldPersistTaps="handled" refreshControl={<RefreshControl refreshing={loading} onRefresh={() => void load()}/>}>
      <Text style={s.sync}>{loading ? 'Consultando la plataforma…' : updated ? `Actualizado ${updated.toLocaleTimeString('es-VE')}` : 'Conectando…'} · Actualización automática</Text>
      {!!error && <Text accessibilityRole="alert" style={s.error}>{error}</Text>}
      {tab === 'directorio' && !doctor && <><Text style={s.heading}>Encuentra a tu especialista</Text><Text style={s.muted}>Médicos y servicios de tu región.</Text><Field placeholder="Nombre, especialidad o código" value={search} onChangeText={setSearch}/><Action title="Buscar médicos" disabled={busy} onPress={() => {setPage(1);setQuery(search.trim());}}/>
        {doctors.map(d => <Pressable key={d.id} accessibilityRole="button" onPress={() => void openDoctor(d)} style={s.card}><View style={s.row}>{d.photoUrl ? <Image source={{uri:d.photoUrl}} style={s.avatar}/> : <View style={[s.avatar,s.initial]}><Text style={s.initialText}>{d.firstName[0]}{d.lastName[0]}</Text></View>}<View style={s.flex}><Text style={s.cardTitle}>Dr(a). {d.firstName} {d.lastName}</Text><Text style={s.muted}>{d.specialties.map(x=>x.specialty.name).join(' · ') || 'Medicina general'}</Text><Text style={s.muted}>{d.municipality || 'Monagas'}</Text><Text style={s.badge}>{d.verificationStatus === 'VERIFIED' ? 'Documentación verificada' : 'Verificación en curso'}</Text></View></View></Pressable>)}
        {!loading && !doctors.length && <Text style={s.muted}>No hay resultados.</Text>}<View style={s.row}><Action title="Anterior" secondary disabled={page<=1} onPress={()=>setPage(p=>p-1)}/><Text>{page} / {Math.max(1,pages)}</Text><Action title="Siguiente" secondary disabled={page>=pages} onPress={()=>setPage(p=>p+1)}/></View></>}
      {tab === 'directorio' && doctor && <><Action title="← Volver al directorio" secondary onPress={()=>{setDoctor(null);setSlots([]);}}/><View style={s.card}><Text style={s.heading}>Dr(a). {doctor.firstName} {doctor.lastName}</Text><Text style={s.muted}>{doctor.specialties.map(x=>x.specialty.name).join(' · ')}</Text><Text style={s.copy}>{doctor.bio}</Text><Text style={s.muted}>{doctor.municipality}</Text></View>{doctor.bookingEnabled ? <><Text style={s.heading}>Solicitar cita</Text><Field placeholder="Fecha AAAA-MM-DD" value={date} onChangeText={setDate}/><Action title="Consultar horarios" secondary onPress={()=>void load()}/>{slots.map(slot=><Action key={slot} title={dateLabel(slot)} disabled={busy} secondary onPress={()=>book(slot)}/>)}{!loading && !slots.length && <Text style={s.muted}>No hay horarios disponibles para esa fecha.</Text>}</> : <Text style={s.muted}>Este médico no tiene reservas online habilitadas.</Text>}{user?.role==='USER'&&<ContactDoctor key={doctor.id} slug={doctor.slug} name={`${doctor.firstName} ${doctor.lastName}`}/>}</>}
      {(tab==='citas'||tab==='avisos') && !user && <><Text style={s.heading}>Tu espacio de salud</Text><Text style={s.copy}>Inicia sesión con la misma cuenta que usas en la web.</Text><Action title="Iniciar sesión" onPress={()=>changeTab('cuenta')}/></>}
      {tab==='citas' && user && <><Text style={s.heading}>{user.role==='PROFESSIONAL'?'Mi agenda · próximos 30 días':'Mis citas'}</Text>{appointments.map(a=><View style={s.card} key={a.id}><Text style={s.cardTitle}>{dateLabel(a.startsAt)}</Text><Text style={s.copy}>{a.professional ? `Dr(a). ${a.professional.firstName} ${a.professional.lastName}` : a.patient?.name || a.patient?.patientCode || a.patientCode || 'Cita'}</Text><Text style={s.badge}>{labels[a.status] || a.status}</Text>{user.role==='PROFESSIONAL'&&<DoctorAppointmentActions id={a.id} status={a.status} onSaved={load}/>}{!['CANCELED','CANCELLED','COMPLETED','NO_SHOW'].includes(a.status)&&<Action title="Cancelar cita" secondary disabled={busy} onPress={()=>Alert.alert('Cancelar cita','¿Quieres cancelar esta cita?', [{text:'Volver',style:'cancel'},{text:'Cancelar cita',style:'destructive',onPress:()=>void run(async()=>{await request(`/appointments/${a.id}/cancel`,'PATCH',{cancellationReason:'Cancelada desde la app'});await load();})}])}/>}</View>)}{!loading&&!appointments.length&&<Text style={s.muted}>No tienes citas en este listado.</Text>}</>}
      {tab==='avisos' && user && <><Text style={s.heading}>Tus avisos</Text>{notices.map(n=><View key={n.id} style={s.card}><Text style={s.cardTitle}>{n.title}</Text><Text style={s.copy}>{n.content}</Text><Text style={s.muted}>{dateLabel(n.createdAt)}</Text>{!n.isRead && <Action title="Marcar como leído" secondary disabled={busy} onPress={()=>void run(async()=>{await request(`/notifications/${n.id}/read`,'PATCH');await load();})}/>}</View>)}{!loading&&!notices.length&&<Text style={s.muted}>No tienes avisos.</Text>}</>}
      {tab==='cuenta' && !user && <><Text style={s.heading}>{challenge?'Verificar acceso':accountFormOpen?'Tu cuenta':'Bienvenido de nuevo'}</Text><Text style={s.copy}>Usa tu cuenta de Guía Médica Monagas.</Text>{challenge ? <><Field placeholder="Código recibido por correo" value={code} onChangeText={setCode}/><Action title="Verificar código" disabled={busy} onPress={()=>void mfa()}/><Action title="Volver" secondary onPress={()=>setChallenge(null)}/></> : <>{!accountFormOpen&&<><Field placeholder="Correo electrónico" value={email} onChangeText={setEmail}/><Field placeholder="Contraseña" value={password} onChangeText={setPassword} secret/><Action title={busy?'Ingresando…':'Entrar'} disabled={busy||!email||!password} onPress={()=>void login()}/></>}<AccountForms onModeChange={setAccountFormOpen} onLogin={async()=>{await session();setTab('citas');}}/></>}</>}
      {tab==='cuenta' && user && <><Text style={s.heading}>Mi cuenta</Text><View style={s.card}><Text style={s.cardTitle}>{user.email}</Text><Text style={s.copy}>{user.role==='PROFESSIONAL'?'Médico':user.role==='USER'?'Paciente':'Cuenta de plataforma'}</Text><Text style={s.muted}>{user.isEmailVerified?'Correo verificado':'Verifica tu correo para completar tu acceso.'}</Text>{user.needsLegalAcceptance&&<Text style={s.error}>Debes revisar y aceptar los textos legales vigentes en la plataforma.</Text>}</View><SecuritySettings/>{user.role==='USER'&&<><PatientAccount email={user.email}/><ContactRequests/></>}<Action title="Gestionar mi perfil en la web" secondary onPress={()=>void Linking.openURL(`${SITE_URL}/${user.role==='PROFESSIONAL'?'dashboard/perfil':'paciente'}`)}/><Action title="Privacidad y gestión de datos" secondary onPress={()=>void Linking.openURL(`${SITE_URL}/privacidad`)}/><Action title="Solicitar eliminación de cuenta" secondary onPress={()=>void Linking.openURL(`${SITE_URL}/reclamos?tipo=ACCOUNT_DELETION`)}/><Action title="Cerrar sesión" disabled={busy} onPress={()=>void run(async()=>{generation.current++;try{await logout();}finally{await forgetSession();setUser(null);setAppointments([]);setNotices([]);setChallenge(null);}})}/></>}
      {busy && <ActivityIndicator color="#125545"/>}<Text style={s.footer}>Guía Médica Monagas · Datos de la plataforma oficial</Text>
    </ScrollView></KeyboardAvoidingView><View style={s.tabs}>{(['directorio','citas','avisos','cuenta'] as Tab[]).map(t=><Pressable accessibilityRole="tab" accessibilityState={{selected:tab===t}} key={t} onPress={()=>changeTab(t)} style={s.tab}><Text style={[s.tabText,tab===t&&s.active]}>{({directorio:'Médicos',citas:'Citas',avisos:'Avisos',cuenta:'Cuenta'})[t]}</Text></Pressable>)}</View></SafeAreaView>;
}
const s=StyleSheet.create({root:{flex:1,backgroundColor:'#f6f8f5'},header:{backgroundColor:'#125545'},headerContent:{width:'100%',maxWidth:720,alignSelf:'center',paddingHorizontal:24,paddingTop:16,paddingBottom:24},brand:{color:'#b8dacb',fontSize:12,letterSpacing:3,fontWeight:'700'},title:{color:'#fff',fontSize:32,fontWeight:'700',marginTop:4},subtitle:{color:'#d1e5db',marginTop:6},body:{flex:1},content:{width:'100%',maxWidth:720,alignSelf:'center',padding:20,paddingBottom:35,gap:12},sync:{fontSize:11,color:'#677d74'},heading:{fontSize:24,color:'#153f34',fontWeight:'700'},muted:{fontSize:14,color:'#60746e',lineHeight:21},copy:{fontSize:15,color:'#293f37',lineHeight:23,marginVertical:8},card:{backgroundColor:'#fff',borderRadius:18,padding:18,borderWidth:1,borderColor:'#e0e8df',gap:6},cardTitle:{flexShrink:1,fontSize:17,color:'#193e33',fontWeight:'600'},row:{flexWrap:'wrap',flexDirection:'row',alignItems:'center',gap:12,justifyContent:'space-between'},flex:{flex:1,minWidth:150},avatar:{width:56,height:56,borderRadius:28},initial:{backgroundColor:'#e0eee5',alignItems:'center',justifyContent:'center'},initialText:{fontSize:18,color:'#125545',fontWeight:'700'},badge:{color:'#236d53',fontSize:12,marginTop:7},input:{minHeight:48,backgroundColor:'#fff',borderWidth:1,borderColor:'#cddad1',borderRadius:12,padding:14,fontSize:16,color:'#193e33'},button:{minHeight:48,justifyContent:'center',backgroundColor:'#125545',borderRadius:12,padding:14,alignItems:'center'},secondary:{backgroundColor:'#e7eee7'},buttonText:{color:'#fff',fontSize:14,fontWeight:'600'},error:{color:'#9b2929',backgroundColor:'#ffeded',padding:13,borderRadius:10},tabs:{flexDirection:'row',backgroundColor:'#fff',borderTopWidth:1,borderTopColor:'#dce7dc',paddingBottom:0,paddingTop:8},tab:{flex:1,minHeight:48,justifyContent:'center',paddingVertical:12,alignItems:'center'},tabText:{color:'#6a7b73',fontWeight:'600'},active:{color:'#125545'},footer:{fontSize:11,textAlign:'center',color:'#819087',marginTop:15}});
